services:
  web:
    build: .
    container_name: boxing-web
    command: [ "/entrypoint.sh" ]
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=localhost,127.0.0.1,217.114.4.253,devarena.ru,www.devarena.ru
      - DJANGO_SETTINGS_MODULE=boxing.settings
      - DB_NAME=boxing_db
      - DB_USER=root
      - DB_PASSWORD=12981298
      - DB_HOST=db
      - DB_PORT=5432

  db:
    image: postgres:15
    container_name: boxing-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=boxing_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=12981298

  nginx:
    image: nginx:latest
    container_name: boxing-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
